### Tasks description for Lesson 5:

#### Комментарии:

Задание к уроку 5 выполнено.

В замечаниях к уроку 3 было рекомендовано использовать исключения для оповещения об ошибках каталога. Для того, чтобы отличать их от прочих исключений, я создал свой класс CatalogException. При этом контроллер перехватывает исключения и обрабатывает их так:
- CatalogException связаны с ошибками пользователя (попытка посмотреть или удалить несуществующую категорию, добавить дублирующую и так далее). В этом случае пользователю сообщается, что он сделал не так, и логируется событие уровня Warning. Я выбрал этот уровень из следующих соображений: для меня как разработчика это не ошибка и исправлять программу мне не надо, это штатное поведение при неправильных действиях пользователя, так что для меня это не Error, а только Warning.
- А вот прочие исключения (если вдруг случатся) - уже неожиданности и связаны с ошибками в программе. Я, правда, такого не видел, но вдруг :)  Поэтому в этом случае пользователю сообщается, что у сервера случилась внутреняя ошибка, логируется подробное событие уровня Error, и система также пытается отправить администратору сервера сообщение по E-Mail через MailNotifier.

Кроме этого, я добавил в разные места кода логирование уровня от Trace до Information. На уровне Trace логируется вся цепочка вызов - из контроллера в модель и дальше в хранилище - так что на этом уровне можно при необходимости трассировать всю последовательность. На уровне Debug логируется создание классов. А на уровне Information логируются крупные события - создание каталога и категорий, вызовы контроллера и отправка e-mail.

Кроме того, при создании исключений CatalogException также записываются сообщения уровня Debug; я не стал делать их уровня Warning/Error, поскольку это сделает контроллер при перехвате исключений, а создавать несколько Warning'ов на одно исключение, по-моему, неправильно. Но если понадобится отследить происхождение исключения - тогда можно включить более детальное логирование и увидеть отправку исключений на уровне Debug.

Остальное сделано в соответствии с лекцией. Конфигурацию Serilog я всю сделал в коде, json файлы править не стал. Параметры e-mail перенесены в секретное хранилище, я проверил, сработало. И три попытки на отправку e-mail добавлены; поскольку на лекции было показано, как использовать Polly с async-вызовами, я переделал отправку на async, надеюсь, что правильно. Но, чтобы не переписывать вызывающий код, я сделал простую обертку async-метода в синхронный и извне уже пользуюсь им.